/* Data Sandbox MVP uses the same local SQLite schema in P2P mode. */

create table if not exists ds_sandbox_image (id varchar(64) primary key, name varchar(128) not null, image_ref varchar(512) not null, kuscia_app_image varchar(128) default '', description varchar(512) default '', enabled integer not null default 1, created_by varchar(128) default '', created_at varchar(32) not null, updated_at varchar(32) not null);
create table if not exists ds_sandbox (id varchar(64) primary key, name varchar(128) not null, owner_id varchar(128) not null, project_id varchar(64) default '', image_id varchar(64) not null, status varchar(32) not null, expires_at varchar(32) not null, network_policy varchar(32) not null default 'INTERNAL_ONLY', cpu_cores real not null default 1, memory_gb real not null default 2, gpu_count integer not null default 0, storage_gb real not null default 10, kuscia_job_id varchar(128) default '', endpoint varchar(512) default '', last_error varchar(1024) default '', created_by varchar(128) default '', created_at varchar(32) not null, updated_at varchar(32) not null, deleted integer not null default 0);
create index if not exists idx_ds_sandbox_owner on ds_sandbox(owner_id, deleted);
create index if not exists idx_ds_sandbox_status on ds_sandbox(status, deleted);
create table if not exists ds_sandbox_snapshot (id varchar(64) primary key, sandbox_id varchar(64) not null, status varchar(32) not null, artifact_path varchar(1024) not null, size_bytes integer not null default 0, checksum varchar(128) default '', created_by varchar(128) default '', created_at varchar(32) not null);
create table if not exists ds_resource_pool (resource_type varchar(32) primary key, total_amount real not null, unit varchar(32) not null, warning_threshold real not null default 80, enabled integer not null default 1, updated_at varchar(32) not null);
create table if not exists ds_resource_quota (owner_id varchar(128) primary key, cpu_cores real not null default 16, memory_gb real not null default 64, gpu_count integer not null default 0, storage_gb real not null default 1024, updated_by varchar(128) default '', updated_at varchar(32) not null);
create table if not exists ds_alert_event (id varchar(64) primary key, severity varchar(16) not null, source varchar(64) not null, title varchar(256) not null, detail varchar(1024) default '', status varchar(16) not null default 'OPEN', created_at varchar(32) not null, resolved_at varchar(32) default '');
create table if not exists ds_model_approval (id varchar(64) primary key, model_id varchar(128) not null, model_name varchar(256) not null, project_id varchar(128) default '', version integer not null default 1, status varchar(32) not null, current_stage varchar(32) not null, description varchar(1024) default '', submitter varchar(128) not null, reviewer varchar(128) default '', review_comment varchar(1024) default '', submitted_at varchar(32) not null, updated_at varchar(32) not null, published_at varchar(32) default '');
create index if not exists idx_ds_model_id on ds_model_approval(model_id);
create index if not exists idx_ds_model_status on ds_model_approval(status);
create table if not exists ds_model_approval_history (id integer primary key autoincrement, approval_id varchar(64) not null, action varchar(32) not null, from_status varchar(32) default '', to_status varchar(32) not null, operator varchar(128) not null, comment varchar(1024) default '', created_at varchar(32) not null);
create table if not exists ds_unified_log (id integer primary key autoincrement, log_type varchar(16) not null, level varchar(16) not null default 'INFO', actor varchar(128) default '', action varchar(128) not null, resource_type varchar(64) default '', resource_id varchar(128) default '', detail varchar(2048) default '', ip_address varchar(64) default '', trace_id varchar(128) default '', success integer not null default 1, created_at varchar(32) not null);
create index if not exists idx_ds_log_type_time on ds_unified_log(log_type, created_at);
create index if not exists idx_ds_log_actor on ds_unified_log(actor);
create table if not exists ds_log_retention (log_type varchar(16) primary key, retention_days integer not null, updated_by varchar(128) default '', updated_at varchar(32) not null);
create table if not exists ds_api_client (id varchar(64) primary key, name varchar(128) not null, client_id varchar(128) not null unique, secret_hash varchar(128) not null, scopes varchar(1024) default '', enabled integer not null default 1, last_used_at varchar(32) default '', created_by varchar(128) default '', created_at varchar(32) not null);
create table if not exists ds_webhook (id varchar(64) primary key, name varchar(128) not null, url varchar(1024) not null, events varchar(1024) not null, secret varchar(256) default '', enabled integer not null default 1, created_by varchar(128) default '', created_at varchar(32) not null, updated_at varchar(32) not null);
create table if not exists ds_webhook_delivery (id varchar(64) primary key, webhook_id varchar(64) not null, event_type varchar(128) not null, payload varchar(4096) default '', status varchar(32) not null, attempts integer not null default 0, response_code integer not null default 0, response_body varchar(2048) default '', next_retry_at varchar(32) default '', created_at varchar(32) not null, updated_at varchar(32) not null);
create table if not exists ds_oidc_config (id integer primary key check (id = 1), issuer varchar(1024) default '', client_id varchar(256) default '', client_secret varchar(512) default '', scopes varchar(512) default 'openid profile email', enabled integer not null default 0, discovery_status varchar(32) default 'UNTESTED', discovery_message varchar(2048) default '', updated_by varchar(128) default '', updated_at varchar(32) not null);
create table if not exists ds_backup (id varchar(64) primary key, backup_type varchar(32) not null, status varchar(32) not null, artifact_path varchar(1024) not null, size_bytes integer not null default 0, checksum varchar(128) default '', message varchar(1024) default '', created_by varchar(128) default '', created_at varchar(32) not null, completed_at varchar(32) default '');
create table if not exists ds_support_ticket (id varchar(64) primary key, title varchar(256) not null, category varchar(64) not null, priority varchar(16) not null, description varchar(2048) not null, status varchar(32) not null default 'OPEN', submitter varchar(128) default '', assignee varchar(128) default '', resolution varchar(2048) default '', created_at varchar(32) not null, updated_at varchar(32) not null);

insert or ignore into ds_sandbox_image values ('img-jupyter-scipy', 'Jupyter SciPy', 'quay.io/jupyter/scipy-notebook:2024-10-07', '', 'Python/Jupyter 数据分析环境', 1, 'system', datetime('now'), datetime('now'));
insert or ignore into ds_sandbox_image values ('img-secretflow', 'SecretFlow Runtime', 'secretflow/secretflow-anolis8:latest', 'secretflow', 'SecretFlow 隐私计算环境', 1, 'system', datetime('now'), datetime('now'));
insert or ignore into ds_resource_pool values ('CPU', 64, '核', 80, 1, datetime('now'));
insert or ignore into ds_resource_pool values ('MEMORY', 256, 'GB', 80, 1, datetime('now'));
insert or ignore into ds_resource_pool values ('GPU', 4, 'A100', 80, 1, datetime('now'));
insert or ignore into ds_resource_pool values ('STORAGE', 36864, 'GB', 85, 1, datetime('now'));
insert or ignore into ds_log_retention values ('OPERATION', 180, 'system', datetime('now'));
insert or ignore into ds_log_retention values ('AUDIT', 365, 'system', datetime('now'));
insert or ignore into ds_log_retention values ('LOGIN', 180, 'system', datetime('now'));
insert or ignore into ds_log_retention values ('SYSTEM', 90, 'system', datetime('now'));
insert or ignore into ds_oidc_config(id, updated_at) values (1, datetime('now'));
