/*
 * Copyright 2026 Ant Group Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 */

package org.secretflow.secretpad.web.service.dev;

import java.util.regex.Pattern;

/**
 * Z-05 函数开发（UDF）Python 包装器生成器。
 *
 * <p>JVM 进程内无法执行用户 Python 函数（{@code sqlite3.Connection.create_function} 是 Python
 * API），因此 FUNCTION 任务由后端生成一个包装脚本，复用既有 python-runner pod 执行：包装器
 * 以只读方式打开沙箱 DB 快照 {@code SANDBOX_DB_PATH} → {@code conn.create_function} 注册用户
 * 函数 → 执行服务端预渲染 SQL（参数已插值、行数已 LIMIT 封顶）→ 导出结果 CSV 到 {@code --output}。
 * DB 快照缺失时回退旧 CSV 直通模式（读 {@code --input} 原样透传），保证老 runner 亦不失败。</p>
 */
public final class DevFunctionWrapper {

    private DevFunctionWrapper() {
    }

    /** Python 标识符（函数名需与 SQL 中调用名一致）。 */
    private static final Pattern FN_NAME = Pattern.compile("[A-Za-z_][A-Za-z0-9_]*");

    /** SQLite UDF 参数个数上限（SQLite 内置 0..127）。 */
    private static final int MAX_NARGS = 127;

    /**
     * 生成包装脚本。
     *
     * @param functionName  用户函数名（Python 标识符，SQL 中以同名调用）
     * @param nargs         函数参数个数（SQLite UDF 约定 0..127）
     * @param functionSource 用户函数定义源码（顶层 import + def，原样内嵌）
     * @param renderedSql   服务端已渲染有界 SQL（{@link DevSqlEngine#renderBounded} 产物）
     * @return 包装脚本全文（由 python-runner pod 执行）
     */
    public static String generate(String functionName, int nargs,
            String functionSource, String renderedSql) {
        if (functionName == null || !FN_NAME.matcher(functionName).matches()) {
            throw new IllegalArgumentException(
                    DevErrors.DEV_PARAM_INVALID + ": 函数名非法: " + functionName);
        }
        if (nargs < 0 || nargs > MAX_NARGS) {
            throw new IllegalArgumentException(
                    DevErrors.DEV_PARAM_INVALID + ": 函数参数个数非法: " + nargs);
        }
        if (functionSource == null || functionSource.isBlank()) {
            throw new IllegalArgumentException(
                    DevErrors.DEV_PARAM_INVALID + ": 函数源码为空");
        }
        if (renderedSql == null || renderedSql.isBlank()) {
            throw new IllegalArgumentException(
                    DevErrors.DEV_PARAM_INVALID + ": 函数 SQL 为空");
        }

        StringBuilder sb = new StringBuilder();
        sb.append("# Generated by DataSandbox DevFunctionWrapper. Do not edit.\n");
        sb.append("import argparse, csv, json, os, sqlite3\n");
        sb.append("\n");
        sb.append(functionSource.stripTrailing());
        sb.append("\n\n");
        sb.append("def _main():\n");
        sb.append("    ap = argparse.ArgumentParser()\n");
        sb.append("    ap.add_argument('--input', required=True)\n");
        sb.append("    ap.add_argument('--output', required=True)\n");
        sb.append("    ap.add_argument('--params', default='{}')\n");
        // runner 会透传 --input-table 等额外参数，解析器须容忍未知参数
        sb.append("    a, _ = ap.parse_known_args()\n");
        sb.append("    header = []\n");
        sb.append("    rows = []\n");
        sb.append("    db = os.environ.get('SANDBOX_DB_PATH', '')\n");
        sb.append("    if db and os.path.exists(db):\n");
        sb.append("        conn = sqlite3.connect('file:' + db + '?mode=ro', uri=True)\n");
        sb.append("        conn.execute('PRAGMA query_only=ON')\n");
        sb.append("        conn.create_function('").append(functionName).append("', ")
                .append(nargs).append(", ").append(functionName).append(")\n");
        sb.append("        cur = conn.execute(").append(pyStr(renderedSql)).append(")\n");
        sb.append("        header = [d[0] for d in cur.description]\n");
        sb.append("        rows = [list(r) for r in cur.fetchall()]\n");
        sb.append("        conn.close()\n");
        sb.append("    else:\n");
        sb.append("        with open(a.input, encoding='utf-8') as f:\n");
        sb.append("            r = csv.DictReader(f)\n");
        sb.append("            header = r.fieldnames or []\n");
        sb.append("            rows = [list(x.values()) for x in r]\n");
        sb.append("    with open(a.output, 'w', newline='', encoding='utf-8') as f:\n");
        sb.append("        w = csv.writer(f)\n");
        sb.append("        w.writerow(header)\n");
        sb.append("        w.writerows(rows)\n");
        sb.append("\n");
        sb.append("if __name__ == '__main__':\n");
        sb.append("    _main()\n");
        return sb.toString();
    }

    /** 以 Python 双引号字符串字面量形式安全内嵌任意文本（转义反斜杠/引号/换行/控制符）。 */
    private static String pyStr(String s) {
        StringBuilder sb = new StringBuilder("\"");
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '\\' -> sb.append("\\\\");
                case '"' -> sb.append("\\\"");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default -> {
                    if (c < 0x20) {
                        sb.append(String.format("\\x%02x", (int) c));
                    } else {
                        sb.append(c);
                    }
                }
            }
        }
        return sb.append('"').toString();
    }
}
